# Generated by Django 5.2.6 on 2025-09-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('action_do', models.CharField(max_length=100)),
                ('time_do', models.PositiveIntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('award', models.CharField(blank=True, max_length=100, null=True)),
                ('period_days', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
        migrations.CreateModel(
            name='Pleasant_Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('action_do', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'приятная привычка',
                'verbose_name_plural': 'приятные привычки',
            },
        ),
    ]
